export const config = {
  port: Number(process.env.PORT || 8080),
  dataDir: process.env.DATA_DIR || "/data",
  storeName: process.env.MICROCENTER_STORE_NAME || "IL - Chicago",
  intervalSeconds: Math.max(60, Number(process.env.CHECK_INTERVAL_SECONDS || 120)),
  dashboardPassword: process.env.DASHBOARD_PASSWORD || "",
  seedDefaultWatch: (process.env.SEED_DEFAULT_WATCH || "true").toLowerCase() === "true",
  defaultProductUrl: process.env.DEFAULT_PRODUCT_URL || "https://www.microcenter.com/product/713503/nintendo-pokemon-mega-evolution-pitch-black-elite-trainer-box",
  discordToken: process.env.DISCORD_TOKEN || "",
  discordChannelId: process.env.DISCORD_CHANNEL_ID || "",
  vapidPublicKey: process.env.VAPID_PUBLIC_KEY || "",
  vapidPrivateKey: process.env.VAPID_PRIVATE_KEY || "",
  vapidSubject: process.env.VAPID_SUBJECT || "",
  emailEnabled: (process.env.EMAIL_ALERTS_ENABLED || "false").toLowerCase() === "true",
  emailTo: process.env.EMAIL_TO || "",
  smtpHost: process.env.SMTP_HOST || "",
  smtpPort: Number(process.env.SMTP_PORT || 587),
  smtpSecure: (process.env.SMTP_SECURE || "false").toLowerCase() === "true",
  smtpUser: process.env.SMTP_USER || "",
  smtpPass: process.env.SMTP_PASS || "",
  emailFrom: process.env.EMAIL_FROM || ""
};
